name: Build FFmpeg AAR (GPL Enabled, arm64-v8a)

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # 1️⃣ Checkout FFmpegKit
      - name: Checkout FFmpegKit
        run: |
          git clone --depth=1 https://github.com/arthenica/ffmpeg-kit.git
          cd ffmpeg-kit
          git submodule update --init --recursive

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y autoconf automake build-essential pkg-config \
            cmake yasm nasm python3 python3-pip unzip git wget texinfo \
            libtool libssl-dev zlib1g-dev

      # 3️⃣ Accept GPL license automatically
      - name: Accept GPL License
        run: |
          echo "LICENSE_ACCEPTED=1" >> $GITHUB_ENV
          echo "ANDROID_GPL_ENABLED=1" >> $GITHUB_ENV

      # 4️⃣ Build FFmpegKit for arm64-v8a with GPL & full libraries
      - name: Build FFmpeg AAR
        run: |
          cd ffmpeg-kit
          ./android.sh arm64-v8a --enable-gpl --full

      # 5️⃣ Upload final AAR
      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-kit-gpl-arm64-v8a
          path: ffmpeg-kit/prebuilt/android/ffmpeg-kit-gpl-arm64-v8a.aar
